### ISSUE TITLE
Importing authress-login into Typescript Vue app causes errors in Jetbrains Webstorm

### ISSUE THREAD

**Issue by GrahamLea** [Authress/authress-login.js#2]
Steps to reproduce:
* Grab the code at https://github.com/GrahamLea/authress-test
* `npm install`
* Open the app in [Jetbrains Webstorm](https://www.jetbrains.com/webstorm/download/)

Expected: Types distributed with `authress-login` should mean that when it's used correctly, no errors show up.

Actual:
1. Importing `LoginClient` is shown as an error:
![image](https://user-images.githubusercontent.com/754403/111304579-04525900-86aa-11eb-80c8-7a7a76612188.png)

2. A call to `authenticate()` shows a warning on the type of the object passed in:
![image](https://user-images.githubusercontent.com/754403/111304837-51362f80-86aa-11eb-8d88-b5d3722631f9.png)

It's possible it's a Webstorm problem, but I haven't seen a problem like this with any other libraries, so it seems like the types distributed with `authress-login` would be the most likely cause / best starting point.

**Comment by wparad** [comment]
This has been resolved in version `1.0.32`. There was an issue with the JSDoc definition, even though the type declaration was correct. It seems that by default Webstorm cares more about that. We've gone and corrected the problem anyway. Personally I'm still looking for the best "official way" to make changes to the `index.d.ts` that reflects the reality, but working examples of this are scarce.

**Comment by GrahamLea** [comment]
Works great. Thanks!
