### ISSUE TITLE
missing inviteId parameter in authenticate method 

### ISSUE THREAD

**Issue by beardedhorseman** [Authress/authress-login.js#56]
In the authress  [documentation](https://authress.io/knowledge-base/docs/usage-guides/onboarding-users#5-inviting-other-users-into-the-shared-account) for sending invitations , it is stated that we can pass the inviteId to the authenticate method to log an invited user in, but inviteId is missing in the list of parameters that can be passed to the sdk's authenticate method.
```

` 
interface AuthenticationParameters {

  connectionId?: string;

  tenantLookupIdentifier?: string;

  responseLocation?: string;

  flowType?: string;

  redirectUrl?: string;

  connectionProperties?: Record<string, string>;

  force?: boolean;

  multiAccount?: boolean;

  clearUserDataBeforeLogin?: boolean;
}
`
```

**Comment by wparad** [comment]
Fixed with #55. Thank you for reporting this. This should now be available in the latest version. However if there are still issues please let us know.
